### ISSUE TITLE
Use `torchmetrics` in `baal.metrics`

### ISSUE THREAD

**Issue by Dref360** [baal-org/baal#156]
We should swap most of our metrics for `torchmetrics` this would make our code more robust.

Only ECE is special I think and we should keep our own implementation.

**Comment by GeorgePearse** [comment]
I'd like to take this if no one's got started on it?

**Comment by Dref360** [comment]
Sounds good, what I was thinking was the following:

* Add torchmetrics as a dependency (poetry add torchmetrics)
* Make sure that baal.modelwrapper.ModelWrapper._update_metrics and _reset_metrics works with PL metrics and ours for backward compatibility.
* Update experiment scripts to match the new PL.

**Comment by Dref360** [comment]
I just wrote the following Baal metrics that leverage torchmetrics.

We have very similar APIs so I think its a good idea to scrap Baal metrics in favor of torchmetrics. Wyt? 

```
 from typing import List
 
 import numpy as np
 import torch
 from torchmetrics import Accuracy
 from torchmetrics.functional import auc
 
 from baal.utils.metrics import Metrics
 
 
 class AccuracyAUC(Metrics):
     def __init__(self, thresholds: List[float], **kwargs):
         self.thresholds = thresholds
         self._accs = [Accuracy(threshold=th) for th in thresholds]
         super().__init__(**kwargs)
 
     def reset(self):
         for acc in self._accs:
             acc.reset()
 
     def update(self, output=None, target=None):
         for acc in self._accs:
             acc.update(output, target)
 
     @property
     def value(self):
         return auc(torch.FloatTensor(self.thresholds), torch.FloatTensor([acc.compute() for acc in self._accs]),
                    reorder=False).item()
 
 
 random_probs = torch.softmax(torch.randn(100, 10), dim=1)
 random_target = torch.randint(0, 10, (100,))
 
 met = AccuracyAUC(np.linspace(0, 1, 10))
 met.update(random_probs, random_target)
 print(met.value)
```

**Comment by Dref360** [comment]
Hello, I would have time to work on it this week if you are not already started.
