### ISSUE TITLE
Brainstorm about uncertainty for semantic segmentation

### ISSUE THREAD

**Issue by pieterblok** [baal-org/baal#215]
@Dref360 

Really appreciate all the nice work you and your co-developers did on this versatile software library! 

I have a question about the uncertainty sampling for semantic segmentation. I've integrated another semantic segmentation network with BAAL, and by stepping through the code blocks, I found something that raised a question:

Assuming the output-shape of the tensor after the Monte-Carlo dropout sampling is: 
(1, 19, 1024, 1024, 15) 
(batch_size, number_of_classes, image_width, image_height, monte_carlo_iterations)

For what reason does the function **_singlepass_** average across the Monte-Carlo samplings: https://github.com/baal-org/baal/blob/e0db2c8c2ede0702eb137a3e2692dc3f07b3522a/baal/active/heuristics/heuristics.py#L46

I'm using the Entropy heuristic and the tensor after **_singlepass_** goes to:
(1, 19, 1024, 1024)

Wouldn't be better to keep the output of the Monte-Carlo iterations and track whether the output value after softmax (basically the class label) would change across the 15 iterations? In my opinion an uncertain image would be where the class labels would change across the Monte-Carlo iterations, I guess I would be less interested in measuring the average change in entropy values. 

I just wanna brainstorm about what would makes sense as an uncertainty metric for semantic segmentation... (and whether I should build this, or just re-use a default heuristic from BAAL if your experience with that heuristic is better in the context of semantic segmentation)

**Comment by Dref360** [comment]
Hello,

I think what you are describing is [BALD, Houlsby et al.](https://arxiv.org/abs/1112.5745). It measures the disagreement between predictions.

We use `singlepass` on Entropy to create a Bayesian Model Average, this average is often better than a single prediction.
It is a common baseline in industry and in academia.

In practice, BALD is (almost) always better than Entropy

**Comment by Dref360** [comment]
Great! Let us know how it goes please :) 


Do you have an idea on how we could make this information more available on our documentation? This muat surely be a common question
