### ISSUE TITLE
Improve look of documentation website

### ISSUE THREAD

**Issue by Dref360** [baal-org/baal#216]
We have several possibilities:

* Move to [Mkdocs Material](https://squidfunk.github.io/mkdocs-material/)
* Update our CSS

In all cases, we should redo the tree structure to be more "Profesh"

**Comment by Dref360** [comment]
Using mkdocs-material I can get this type of look.

What do we think about it?

![image](https://user-images.githubusercontent.com/8976546/174495789-626ace18-8130-4fee-9d2f-1848c94c3e20.png)

**Comment by Dref360** [comment]
I made a lot of work on the branch docs/mkdocs, would appreciate if someone would run it locally and give some feedback. I'll continue next week.

**Comment by GeorgePearse** [comment]
Will run locally tonight

**Comment by Dref360** [comment]
Maybe `poetry clean --all` ?

**Comment by GeorgePearse** [comment]
There's the double "None" on the tutorials page.  Also lemme if you know about loose ends and would prefer feedback on what's already there / looks complete.

<img width="1154" alt="image" src="https://user-images.githubusercontent.com/47161914/177048745-e20fdf5f-0bba-491a-ab93-d0676dbfd83d.png">

**Comment by GeorgePearse** [comment]
Would be really nice to either have a timeline for the papers, or a grid with links to them and some categorisation in terms of the types of content / focus of the techniques.

**Comment by GeorgePearse** [comment]
Another None 
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/47161914/177049530-a87cb496-9eba-4d3c-ad91-4086110e7ba2.png">

**Comment by GeorgePearse** [comment]
I don't see a "Getting started" type tab, or an installation (just with a link to https://pypi.org/project/baal/)

**Comment by Dref360** [comment]
Forgot to commit the symlink to `notebooks`. just fixed many issues as well.
