### ISSUE TITLE
"stable_badge" branch poetry sklearn requirements update

### ISSUE THREAD

**Issue by zia-hasan** [baal-org/baal#224]
**Is your feature request related to a problem? Please describe.**
I am trying to develop an application using baal but the stable_badge branch only supports a lower version of sklearn and it is causing some conflicts with master branch

**Describe the solution you'd like**
We have, scikit-learn = "^0.24.2" in pyproject.toml. I would like this to be same as master branch >1.0

**Describe alternatives you've considered**
N/A

**Comment by Dref360** [comment]
Hi Zia, I just merged master on the branch and it should work as expect now. Please let me know if that fixes it. I was able to `poetry install` on my side.

**Comment by Dref360** [comment]
Closing, let me know if there are other issues.
