### ISSUE TITLE
Add EPIG 

### ISSUE THREAD

**Issue by Dref360** [baal-org/baal#259]
This could unlock some new opportunities for us, particularly for Transformers.

[Github](https://github.com/fbickfordsmith/epig)
[Paper](https://arxiv.org/abs/2304.08151)

**Comment by reeshipaul** [comment]
I would like to work on this implementation

**Comment by Dref360** [comment]
Awesome!
Thank you very much :)

**Comment by Dref360** [comment]
I'll read the full paper over the weekend. I would know more about how we could work on this.

**Comment by Dref360** [comment]
After reading the paper and looking at the codebase, I think the main issue is that we can't easily supply all `targets` to the heuristic.

We could directly provide the active dataset to the heuristic and then iterate over it when we call `EPIG(active_set=active_set).get_scores(predictions)`. 

What do you think? I don't think this is the perfect solution so I can be easily persuaded to go another route.

**Comment by reeshipaul** [comment]
I have read the paper, will read it in depth once more till the weekend. Can we schedule a meet over the weekend to discuss about the implementation?

**Comment by Dref360** [comment]
Sounds good! 

My calendar is available on Calendly: https://calendly.com/baal-org/30min?month=2023-05

If these don't work for you let me know and we will figure something out :) We can chat on Slack as well.

**Comment by reeshipaul** [comment]
@Dref360 can you please send out an invite for slack to reeshipaul35@gmail.com

**Comment by Dref360** [comment]
Fixed in #270 thank you @reeshipaul for the PR!
